version: '3.8'

services:
  backend:
    build: .
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.venv
    command: python app.py
    
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    
  db:
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
